залил готовый проект
KirstonMoon/FocusStartHomeworks pull request #1
Opened 2020-10-22 17:42 UTC by KirstonMoon

2020-11-09 15:46 UTC, Viscount88 requested changes

2020-11-09 15:46 UTC, Viscount88 commented on CarForFS/Controllers/MainViewController.swift
> +    var filterHatchback: [Car] = []
А если фильтров будет пара сотен - тоже будешь для каждого массив делать?:) У тебя идёт фильтрация по определенному признаку - тебе нужно при показе таблицы взять массив allCars, проверить наличие фильтра и в случае наличия - пройтись по массиву и отфильтровать его. Например это может выглядеть примерно так: let filteredCars = allCars.filter { $0.model = <Выбранный в фильтрах корпус> }. То есть на данный момент тебе здесь нужен один массив allCars и сохраненный выбранный фильтр(опциональный, т.к. может не быть фильтра). Фильтры у тебя насколько я вижу вообще пока не работают, но суть должна быть такая: ты на экране фильтров делаешь выбор и передаёшь выбранный фильтр на этот экран. При загрузке экрана мы берем массив всех добавленных тачек и смотрим фильтр - если он есть - делаем фильтрацию примерно как я показал выше. Можно завести ещё 1 вспомогательный массив - общий filteredCars, в который при входе на экран будут сохраняться автомобили, соответствующие фильтры - это облегчит жизнь в том плане, что при определении кол-ва ячеек у таблицы и показа самих ячеек - мы будем просто брать всё что есть в filteredCars.

2020-11-09 15:46 UTC, Viscount88 commented on CarForFS/Controllers/MainViewController.swift
> +        allCars.insert(newCarVC.newCar!, at: 0)
Не используй force unwrap - тут вполне может не оказаться этого newCar, он у тебя опциональный. Пройдись гвардом или условным оператором, проверь его наличие и если он есть - тогда добавляй в массив.

2020-11-09 15:46 UTC, Viscount88 commented on CarForFS/Controllers/MainViewController.swift
> +        newCarVC.saveCar()
Этот контроллер ни в коем случае не должен управлять другим. Кроме того тебе вообще не нужно сохранять там автомобиль - ты можешь передать его как параметр при переходе по segue например, если уж ты выбрал такой способ навигации.

2020-11-09 15:46 UTC, Viscount88 commented on CarForFS/Controllers/MainViewController.swift
> +    @IBAction func unwindSegueFromFilterVC(_ segue: UIStoryboardSegue) {
Не нужно здесь всё это, также параметром в переходм передаешь выбранный тип кузова и уже внутри этого контроллера фильтруешь машины по нему и с этим работаешь.

2020-11-09 15:46 UTC, Viscount88 commented on CarForFS/Controllers/MainViewController.swift
> +    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
У тебя получается часть данных выводится на экран, а часть просто принтом в консоль - выглядит очень странно)

2020-11-09 15:46 UTC, Viscount88 commented on CarForFS/Controllers/MainViewController.swift
> +        if car.carNumber == "" {
тут тогда лучше так: if !car.carNumber.isEmpty { <Вывести номер машины> }, а в else можно вообще ничего не делать, т.к. нам по сути нужно ничего не показывать в таком случае. То есть мы проверяем в этом случае, что у сущности поле carNumber не пустое (не нил и не "")

2020-11-09 15:46 UTC, Viscount88 commented on CarForFS/Models/CarsModel.swift
> +enum Body {
Сделай этот енам типа String, и CaseIterable. Первое позволит тебе брать значение енама по rawValue в виде строки, второе - получить все кейсы в виде массива строк через Body.allCases

2020-11-09 15:46 UTC, Viscount88 commented on CarForFS/Controllers/NewCarViewController.swift
> +    var carBodyTypes = ["Hatchback", "Sedan", "Coupe", "Jeep", "Wagon"]
Этот массив не нужен, читай комменты к енаму Body

2020-11-09 15:46 UTC, Viscount88 commented on CarForFS/Controllers/NewCarViewController.swift
> +    var selectedElement: String?
Не нужно сохранять выбранное в пиккере значение - сделай как я написал для енама, тогда сможешь смотреть что введено в поле body и по строке находить соответствующее значение в енаме и уже его передавать дальше.

2020-11-09 15:46 UTC, Viscount88 commented on CarForFS/Controllers/NewCarViewController.swift
> +    func pickerView(_ pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int {
тут получается после изменений в енаме будет просто Body.allCases.count

2020-11-10 09:54 UTC, KirstonMoon commented on CarForFS/Controllers/NewCarViewController.swift
> +    func pickerView(_ pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int {
подписал энам под string и caseIterable но
в методе titleForRow я пытаюсь назначить полям имена типов кузовов используя Body.allCases[row].rawValue
но в итоге вижу только знаки вопроса "?" подскажите? что можно тут сделать?)

2020-11-10 18:25 UTC, KirstonMoon commented
решил полностью переписать приложение так как реализация 50% в UI и 50% в консоле заведомо была обречена на провал
перепроверьте пожалуйста текущий вариант

2020-11-13 06:08 UTC, Viscount88 requested changes
уже лучше, но надо поправить критические замечания, опциональные можно править, можно не править.

2020-11-14 14:51 UTC, KirstonMoon commented on FocusStartHomework-1/CarForFS/Controllers/FilterBodyViewController.swift
> +        guard selectedBodyFromPicker != nil else { return }
исправил

2020-11-14 14:51 UTC, KirstonMoon commented on FocusStartHomework-1/CarForFS/Controllers/FilterBodyViewController.swift
> +    @IBAction func buttonAction(_ sender: UIButton) {
исправил

2020-11-14 14:53 UTC, KirstonMoon commented on FocusStartHomework-1/CarForFS/Controllers/NewCarViewController.swift
> +        chooseCarBody()
исправил

2020-11-14 15:11 UTC, KirstonMoon commented on FocusStartHomework-1/CarForFS/Controllers/DetailViewController.swift
> +    var manufacturer: String?
исправил

2020-11-14 15:11 UTC, KirstonMoon commented on FocusStartHomework-1/CarForFS/Controllers/DetailViewController.swift
> +        manufacturerLabel.text = "Manufacturer: \(manufacturer!)"
исправил

2020-11-14 15:14 UTC, KirstonMoon commented on FocusStartHomework-1/CarForFS/Controllers/FilterBodyViewController.swift
> +        filteredCarsArray = allCarsArray.filter { $0.body == bodyType }
не совсем понял что нужно тут исправить (

2020-11-14 15:15 UTC, KirstonMoon commented on FocusStartHomework-1/CarForFS/Controllers/MainTableViewController.swift
> +            detailVC.manufacturer = allCars[indexPath.row].manufacturer
исправил

2020-11-14 15:17 UTC, KirstonMoon commented on FocusStartHomework-1/CarForFS/Controllers/FilterBodyViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "filterCell", for: indexPath)
а тогда зачем детаил экран делать если изначально все в ячейке tableview будет отображаться?)

2020-11-14 15:20 UTC, KirstonMoon commented on FocusStartHomework-1/CarForFS/Controllers/MainTableViewController.swift
> +            filterVC.allCarsArray = self.allCars
не могу пока представить как это выглядит, разве плоха текущая реализация, что мы просто передаем в filter view controller массив со всеми машинами, и в этом же filter view controller уже осуществляем фильтрацию по типу кузова?

2020-11-14 16:38 UTC, KirstonMoon commented on FocusStartHomework-1/CarForFS/Controllers/NewCarViewController.swift
> +        let car = Car(manufacturer: manufacturer.text ?? "Не выран производитель", model: model.text ?? "Не выбрана модель", body: Body(rawValue: body.text!)!, yearOfIssue: Int(yearOfIssue.text!), ca
исправил: машина не сохранится без введенных требуемых полей

2020-11-15 10:36 UTC, Viscount88 requested changes

2020-11-15 10:36 UTC, Viscount88 commented on FocusStartHomework-1/CarForFS/Controllers/DetailViewController.swift
> +        fillInfo(self.car!)
Нигде кроме IBOutlet и тп не используй "!" - force unwrap - это вызывает нестабильность работы и попросту не нужно. guard let self.car = car { else return } ...

2020-11-15 10:36 UTC, Viscount88 commented on FocusStartHomework-1/CarForFS/Controllers/DetailViewController.swift
> +        if car.yearOfIssue == nil {
Можно для красоты всё это одной-двумя строками сделать:
let yearString = car.yearOfIssue ? yearNumberText : "-"
yearOfIssueLabel.text = "Year of issue: \(yearString)"

2020-11-15 10:36 UTC, Viscount88 commented on FocusStartHomework-1/CarForFS/Controllers/DetailViewController.swift
> +        if car.carNumber == nil {
Ну тут получается ты дважды одну проверку делаешь, можно же сразу 
guard let numberText = car.carNumber else { 
numberLabel.isHidden = true
return 
}
numberLabel.text = "Number: \(numberText)"

2020-11-15 10:36 UTC, Viscount88 commented on FocusStartHomework-1/CarForFS/Controllers/FilterBodyViewController.swift
> +        filteredCarsArray = allCarsArray.filter { $0.body == bodyType }
Да можно было короче это не делать отдельным методом, а прямо в useFilter сделать. Или сделать метод более универсальным. Но бог с ним, это мелочь.

2020-11-15 10:36 UTC, Viscount88 commented on FocusStartHomework-1/CarForFS/Controllers/FilterBodyViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "filterCell", for: indexPath)
Ну вот как раз если нормально таблицу сделать он особо и не нужен уже будет. Хотя можно будет на экран деталей потом добавить больше полей, некоторые могут не показываться в таблице. Ну тут смотри - юай был необязательным в этом задании - если ты сам хочешь разобраться с ячейками и таблицами - я помогу, если нет - значит этот момент пропускаем и тут смотрим только код.

2020-11-15 10:36 UTC, Viscount88 commented on FocusStartHomework-1/CarForFS/Controllers/MainTableViewController.swift
> +            filterVC.allCarsArray = self.allCars
Ну смотри - у тебя висит таблица на главном экране и ещё одна, по сути такая же на экране фильтров. Если посмотришь на реальные приложения - это всегда будет одна главная талица, а на экране фильтров юзер выбирает именно фильтр, после чего приложение возвращает его на главную таблицу с выбранным фильтром. Ну это уже юай часть, я там выше написал про это - если хочешь разобраться - разбираемся, если нет - в этом дз можем пропустить.

2020-11-15 10:36 UTC, Viscount88 commented on FocusStartHomework-1/CarForFS/Controllers/NewCarViewController.swift
> +            car.carNumber = nil
Зачем? Если ты ничего не передашь - и так нил будет

2020-11-15 10:36 UTC, Viscount88 commented on FocusStartHomework-1/CarForFS/Controllers/NewCarViewController.swift
> +            car.yearOfIssue = nil
Тут тоже что и для кар намбера

2020-11-17 13:31 UTC, KirstonMoon commented on FocusStartHomework-1/CarForFS/Controllers/NewCarViewController.swift
> +            car.carNumber = nil
а это для проверки методом textFieldDidChange

2020-11-17 13:47 UTC, KirstonMoon commented on FocusStartHomework-1/CarForFS/Controllers/DetailViewController.swift
> +        if car.yearOfIssue == nil {
не получилось реализовать данный вариант

2020-11-17 13:48 UTC, KirstonMoon commented
исправил

2020-11-19 18:48 UTC, Viscount88 approved these changes
Критические замечания поправлены

2020-11-26 09:49 UTC, merged