Feature/homework 4 SplitViewController для 4 ДЗ
KirstonMoon/FocusStartHomeworks pull request #8
Opened 2020-11-07 20:21 UTC by KirstonMoon

Реализовал SplitViewController для 4 ДЗ:

Разработать приложение, состоящее из UISplitViewController’a. Где в main показывается UITableView, а в detail уже картинки с тенями.

2020-11-07 20:52 UTC, noreasonwhyiamhere commented
задание принято на проверку)

2020-11-14 00:03 UTC, korshunigor commented
На всякий случай отпишусь, о задании помню, сегодня проверю )

2020-11-14 19:44 UTC, korshunigor requested changes
Правок не много, помимо обозначенного давай еще доработаем так, чтобы при отображении на iPad у нас менюшка отображалась всегда, сбоку (сейчас она в начале отображается, потом скрывается, когда мы просматриваем детали и ее надо снова открывать)

2020-11-14 19:44 UTC, korshunigor commented on FocusStartHomework-4/SplitViewController/Controllers/DetailViewController.swift
> +    func set() {
Можно сделать приватным

2020-11-14 19:44 UTC, korshunigor commented on FocusStartHomework-4/SplitViewController/Controllers/DetailViewController.swift
> +    var cell: CellModel? {
Давай назовем просто `model`, т.к. сейчас название сбивает с толку "что это за ячейка?"

2020-11-14 19:44 UTC, korshunigor commented on FocusStartHomework-4/SplitViewController/Controllers/DetailViewController.swift
> +        DispatchQueue.main.async {
Тут вроде не обязательно

2020-11-14 19:44 UTC, korshunigor commented on FocusStartHomework-4/SplitViewController/Controllers/DetailViewController.swift
> +            self.firstImage.image = self.cell?.firstImage
Давай приведем код к единому стилю, либо всегда обращаемся к `self.`, либо от сюда стоит убрать (первый вариант предпочтителен)

2020-11-14 19:44 UTC, korshunigor commented on FocusStartHomework-4/SplitViewController/Supporting Files/SceneDelegate.swift
> +               let detailViewController = (splitViewController.viewControllers.last as? UINavigationController)?.topViewController as? DetailViewController else { fatalError()}
Давай перенесем else `else { fatalError() }` на новую строку, для более удобного чтения кода, ну и было бы не плохо указать краткий комментарий почему мы фаталим

2020-11-14 19:44 UTC, korshunigor commented on FocusStartHomework-4/SplitViewController/Supporting Files/CustomColor.swift
> +class ShadowViewUIImage: UIImageView {
Как по мне "UIImageWithShadowView" было бы немного лучше, но тут дело вкуса =)

2020-11-14 19:44 UTC, korshunigor commented on FocusStartHomework-4/SplitViewController/Protocols/CellObjectSelectedProtocol.swift
> +import Foundation
Можно удалить

2020-11-14 19:44 UTC, korshunigor commented on FocusStartHomework-4/SplitViewController/Protocols/CellObjectSelectedProtocol.swift
> +protocol CellObjectSelectedDelegate: class {
Протокол для делегатов класса `MasterTableViewController`, по этому думаю стоит переименовать его в `MasterTableViewDelegate`

2020-11-14 19:44 UTC, korshunigor commented on FocusStartHomework-4/SplitViewController/Protocols/CellObjectSelectedProtocol.swift
> +    func cellObjectSelected(cell: CellModel)
Этим методом мы передаем не ячейку, а модельку данных, по этому входной параметр стоит переименовать + этим методом по идее мы вызываем отображение передаваемых данных, стоит это отразить в названии

2020-11-14 19:44 UTC, korshunigor commented on FocusStartHomework-4/SplitViewController/Controllers/MasterTableViewController.swift
> +    let allCells = CellModel.getCell()
Давай отделим let от var пустой строкой. 
`allCells` можно сделать приватным.

2020-11-14 19:44 UTC, korshunigor commented on FocusStartHomework-4/SplitViewController/CellModels/CellModel.swift
> +        let firstCell = CellModel(title: "Заголовок 1", text: "\(lotsOfText)",
Давай для удобства чтения каждый параметр вынесем на отдельную строку

2020-11-17 11:51 UTC, KirstonMoon commented on FocusStartHomework-4/SplitViewController/Controllers/DetailViewController.swift
> +    func set() {
исправил

2020-11-17 11:52 UTC, KirstonMoon commented on FocusStartHomework-4/SplitViewController/Controllers/DetailViewController.swift
> +    var cell: CellModel? {
исправил

2020-11-17 11:52 UTC, KirstonMoon commented on FocusStartHomework-4/SplitViewController/Controllers/DetailViewController.swift
> +        DispatchQueue.main.async {
исправил

2020-11-17 11:54 UTC, KirstonMoon commented on FocusStartHomework-4/SplitViewController/Controllers/DetailViewController.swift
> +            self.firstImage.image = self.cell?.firstImage
исправил

2020-11-17 11:56 UTC, KirstonMoon commented on FocusStartHomework-4/SplitViewController/Supporting Files/SceneDelegate.swift
> +               let detailViewController = (splitViewController.viewControllers.last as? UINavigationController)?.topViewController as? DetailViewController else { fatalError()}
исправил

2020-11-17 11:56 UTC, KirstonMoon commented on FocusStartHomework-4/SplitViewController/Protocols/CellObjectSelectedProtocol.swift
> +import Foundation
исправил

2020-11-17 11:57 UTC, KirstonMoon commented on FocusStartHomework-4/SplitViewController/Protocols/CellObjectSelectedProtocol.swift
> +protocol CellObjectSelectedDelegate: class {
исправил

2020-11-17 11:59 UTC, KirstonMoon commented on FocusStartHomework-4/SplitViewController/Protocols/CellObjectSelectedProtocol.swift
> +    func cellObjectSelected(cell: CellModel)
исправил

2020-11-17 12:01 UTC, KirstonMoon commented on FocusStartHomework-4/SplitViewController/Controllers/MasterTableViewController.swift
> +    let allCells = CellModel.getCell()
строку добавил
а приватным сделать нельзя тк идет вызов в sceneDelegate

2020-11-17 12:02 UTC, KirstonMoon commented on FocusStartHomework-4/SplitViewController/CellModels/CellModel.swift
> +        let firstCell = CellModel(title: "Заголовок 1", text: "\(lotsOfText)",
исправил

2020-11-17 12:18 UTC, KirstonMoon commented
не смог только найти как сделать всегда отображение меню

2020-11-23 15:55 UTC, korshunigor commented
> не смог только найти как сделать всегда отображение меню

2020-11-23 15:55 UTC, korshunigor commented
Прошу прощение, случайно пул закрыл, переоткрыл его обратно )

2020-11-23 16:20 UTC, korshunigor requested changes
Давай доделаем отображение обоих экранов при запуске на iPad. Также надо починить сломанные констрейнты (логи в Xcode сыпятся + в сториборде ругается на Detail View Controller)
<img width="645" alt="Снимок экрана 2020-11-23 в 18 58 43" src="https://user-images.githubusercontent.com/17854702/99986864-cced3300-2dc0-11eb-8653-6fac039c83c5.png">

2020-11-23 16:20 UTC, korshunigor commented on FocusStartHomework-4/SplitViewController/Supporting Files/SceneDelegate.swift
> +        else { fatalError()} // fatal because of cant create a window with controllers
Этот коммент можно включить в сам fatalError, чтобы именно как сообщение был

2020-11-23 16:20 UTC, korshunigor commented on FocusStartHomework-4/SplitViewController/Controllers/MasterTableViewController.swift
> +    let allCells = CellModel.getCell()
Ну, на момент когда делалось ревью еще можно было )
Вообще, такой способ установки значений как вытаскивание allCells в SceneDelegate очень не очень, но т.к. тут еще не дошли до архитектур пусть будет так как есть

2020-11-24 09:21 UTC, KirstonMoon commented
исправил

2020-11-25 18:38 UTC, korshunigor approved these changes
Хорошо! Задание выполнено.

2020-12-05 11:38 UTC, merged